services:
  baget:
    build:
      context: ./baget/
      args:
        - BAGET_VERSION=$BAGET_VERSION
    container_name: volcanion-nuget-server
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
    expose:
      - "80"
    ports:
      - "5000:80"
    restart: always

  nginx:
    build:
      context: ./nginx/
      args:
        - NGINX_VERSION=$NGINX_VERSION
    container_name: volcanion-nginx-nuget-server
    ports:
      - "5001:80"
      - "5443:443"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - baget
    restart: always
